[project]
name = "devops-coop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataclasses-json>=0.6.7",
    "flask>=3.1.0",
    "kubernetes>=31.0.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
